[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect API requests to our functions 
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# SPA redirect (everything else goes to index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 